### ISSUE TITLE
The changed code is missing in the PR on SonarCloud for Java repositories

### ISSUE THREAD

**Issue by exadmin** [Netcracker/qubership-workflow-hub#164]
### Describe the bug

Devops workflow action maven-publish has following code

```
inputs:
    ref:
        required: false
        type: string
        default: "main"
...
- name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref}}
          fetch-depth: 0
```
When nothing is passed to "ref" during maven-publish action then "main" branch will be used. It is ok when working only with main-branches. But, when processing PRs we need to specify non-main branch for the Sonar.

Please, make changes in all our repos by adding:

```
ref: ${{ github.head_ref }}
```

Request source: https://github.com/orgs/Netcracker/projects/11/views/8?pane=issue&itemId=107058486&issue=Netcracker%7Cqubership-core-infra%7C8

### To Reproduce

Make PR into java repo, which is registered in the sonar and get coverage metric for the PR's branch.
https://github.com/Netcracker/qubership-core-utils

### Version

?
