### ISSUE TITLE
Create Helm Charts template and reusable Actions/Workflow to run Helm linters

### ISSUE THREAD

**Issue by IldarMinaev** [Netcracker/qubership-workflow-hub#30]
h1 Helm template
Create template of Helm Chart used in QuberShip.
Suggested example (all fields are mandatory to fill):
```
apiVersion: v2
name: qubership-operator
version: 0.10.0
description: Qubership Operator Helm chart for Kubernetes
type: application
home: https://qubership.io/
sources:
  - https://github.com/Netcracker/qubership-operator
maintainers:
  - name: User
icon: https://raw.githubusercontent.com/Netcracker/brandbook/COMMIT_SHA/icon/color/qubership-operator.png
appVersion: 0.9.0
dependencies:
- name: some-dependency
  version: "1.2.3"
  repository: "https://example.com/charts"
```
Values.yaml
```
# List of mandatory variables
```
template/_helper.tpl
```
# Required general templates/functions (import libs example, etc)
```

h1 Linters
Review tools:
* Helm CLI has own linter: https://helm.sh/docs/helm/helm_lint/
* https://github.com/kubescape/kubescape
* https://github.com/zegl/kube-score
* https://github.com/yannh/kubeconform
* https://github.com/stackrox/kube-linter
* https://github.com/FairwindsOps/polaris

h1 Action/Workflow
Reusable Action/Workflow should for Release stage should fail check on:
* not all mandatory (from QuberShip template)) fields filled in Chart.yaml
* not updated HelmVersion
* founded misconfiguration of appVersion and application version used in templates (Check tags on docker images)
