### ISSUE TITLE
Only Russian profanity words checked by Profanity Action

### ISSUE THREAD

**Issue by asatt** [Netcracker/qubership-workflow-hub#48]
### Describe the bug

We found that the default configuration of Profanity Action validates and checks only Russian words

```yaml
with:
  ...
  custom-profane-words-url: https://github.com/Hesham-Elbadawi/list-of-banned-words/raw/refs/heads/master/ru
```

Reference in repository:
https://github.com/Netcracker/qubership-workflow-hub/blob/main/.github/workflows/profanityFilter.yaml#L41C35-L41C115

### To Reproduce

Check the GitHub Actions in the template repository.

### Version

latest

### Logs

-

### Additional information

-
