### ISSUE TITLE
Add Sonar call into maven-publish step

### ISSUE THREAD

**Issue by exadmin** [Netcracker/qubership-workflow-hub#79]
### Is your feature request related to a problem? Please describe

Сейчас вызов сонара приходится описывать отдельным кастомным шагом, пример: https://github.com/Netcracker/qubership-core-utils/blob/main/.github/workflows/build-on-commit.yaml

### Describe the solution you'd like

Необходимо включить вызов сонара в стандартный шаг, чтобы было что-то вроде:
```
jobs:
    mvn:
        uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@main
        with:
            maven-command: "--batch-mode deploy -Dgpg.skip=true SONAR-STEP" // new: sonar step
            server-id: github
            java-version: 17
        secrets:
            maven-token: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} // new: token
```

### Additional information

More details can be provided by Vladislav Larkin, aka @TaurMorchant
